### ISSUE TITLE
Update Multiprocessing to use Ray

### ISSUE THREAD

**Issue by jonn-smith** [broadinstitute/annmas#20]
https://github.com/ray-project/ray

**Comment by jonn-smith** [comment]
This should allow us to use shared memory and not have to copy our data to the other processes.

(suggested by @winni2k)

**Comment by winni2k** [comment]
Just an update on my reading around ray: numpy arrays can be shared most efficiently (single copy to shared memory with subsequent wrapping in memory). Other objects are serialized into shared memory and deserialized out (two copies). Because pysam objects wrap several C structs, I am unsure whether pysam aligned segment objects can be serialized and deserialized without further code.

**Comment by winni2k** [comment]
Here is the page in the ray library that outlines how serialization is done (pickle version 5) and how to write custom serialization functions for tricky objects: https://docs.ray.io/en/master/serialization.html

**Comment by winni2k** [comment]
It looks like the `to_string()` method is [the recommended function for serialization of pysam reads](https://github.com/pysam-developers/pysam/issues/950). So this means that the current implementation is already optimal regarding the number of copies if reads are only used by one thread. The copies are:

1. Load read using htslib
2. Convert read to python string
3. Serialize python string to put it into queue
4. (inside thread) Deserialize python string when grabbing from queue
5. (inside thread) Parse string and convert to pysam object

Using ray, unfortunately, would not change the number of copies made.

I think a more promising approach is to defer SAM record parsing to the thread pool, or to find a way to serialize pysam objects directly to a numpy array.

**Comment by winni2k** [comment]
I performed some profiling just to check if read serialization is even an issue worth spending more time on. Here are the steps I took:

1. Clone the repo (commit `966c5db`)
2. Follow the installation instructions in the README using venv (python version 3.7.3)
3. cd into `tests/test_data`
4. In a second shell install `py-spy` using `pip`
5. In the first shell run `python3 -m annmas annotate -t 1 -o test_output.bam test_input.bam &` and note down the process ID (22219 in this case)
6. In the second shell run `py-spy top --subprocesses --pid 22219`

This is the output I got:

```
Collecting samples from 'python3 -m annmas annotate -t 1 -o test_output.bam test_input.bam' and subprocesses
Total Samples 4200
GIL: 105.00%, Active: 106.00%, Threads: 9, Processes 4

  %Own   %Total  OwnTime  TotalTime  Function (filename:line)
 95.00%  95.00%   40.03s    40.03s   annotate (model.py:275)
  0.00%   0.00%   0.400s    0.660s   split (re.py:213)
  3.00%   3.00%   0.370s     1.03s   annotate (model.py:284)
  2.00%   2.00%   0.320s    0.320s   recv (multiprocessing/connection.py:251)
  0.00%   0.00%   0.220s    0.230s   dumps (multiprocessing/reduction.py:51)
  1.00%   1.00%   0.170s    0.170s   _recv (multiprocessing/connection.py:379)
  0.00%   0.00%   0.150s    0.150s   _compile (re.py:273)
  0.00%   0.00%   0.130s    0.130s   annotate (model.py:278)
  0.00%   0.00%   0.110s    0.110s   _compile (re.py:276)
  0.00%   0.00%   0.100s    0.100s   _write_thread_fn (src/annmas/annotate/command.py:231)
  0.00%   0.00%   0.090s    0.140s   reverse_complement (model.py:332)
```

I think it's clear that in single-worker mode, the vast majority of processing is spent by the `annotate` function, and not by any multiprocessing overhead.

When running with four worker processes, I see similar loading:
```
Collecting samples from 'python3 -m annmas annotate -t 4 -o test_output.bam test_input.bam' and subprocesses
Total Samples 1100
GIL: 374.00%, Active: 378.00%, Threads: 13, Processes 6

  %Own   %Total  OwnTime  TotalTime  Function (filename:line)
338.00% 338.00%   41.43s    41.43s   annotate (model.py:275)
  4.00%  11.00%   0.370s     1.01s   split (re.py:213)
  2.00%   2.00%   0.360s    0.360s   _compile (re.py:273)
  6.00%   6.00%   0.330s    0.330s   dumps (multiprocessing/reduction.py:51)
  7.00%   7.00%   0.300s    0.300s   recv (multiprocessing/connection.py:251)
  5.00%   5.00%   0.270s    0.270s   _compile (re.py:276)
  3.00%  14.00%   0.250s     1.27s   annotate (model.py:284)
  1.00%   1.00%   0.220s    0.220s   _recv (multiprocessing/connection.py:379)
  3.00%   3.00%   0.160s    0.160s   _write_thread_fn (src/annmas/annotate/command.py:231)
  1.00%   1.00%   0.130s    0.130s   annotate (model.py:278)
```

I think we can archive this issue. Ray could be helpful in simplifying syntax with more complex multiprocessing setups, but I don't know if that's planned.

**Comment by winni2k** [comment]
Also, this code scales really well with number of threads:

```
$ python3 -m annmas annotate -t 72 -o test_output.bam test_input.bam
[INFO 2021-02-09 13:34:30 annotate] Invoked via: annmas annotate -t 72 -o test_output.bam test_input.bam
[INFO 2021-02-09 13:34:30 annotate] Running with 72 worker subprocess(es)
[INFO 2021-02-09 13:34:33 annotate] Using default annotation model
Progress: 100 read [00:01, 60.56 read/s]
[INFO 2021-02-09 13:34:35 annotate] Annotated 100 reads with 7203 total sections.
[INFO 2021-02-09 13:34:35 annotate] Done. Elapsed time: 4.06s. Overall processing rate: 24.64 reads/s.
```

This is with 72 hyperthreaded cores (i.e. 36 real cores) on an intel machine.

**Comment by jonn-smith** [comment]
Sounds good.  I'll close it for now and we can revisit it if we have to in the future.
