### ISSUE TITLE
Installation conundrum

### ISSUE THREAD

**Issue by phpeters** [broadinstitute/annmas#206]
Dear all,

First of all, thanks a ton for developing this method and its tool!

Sadly, when installing with python 3.6, I stumbled over this error message:
`No matching distribution found for networkx>=2.8.4 (from pomegranate->maslongbow)`    (see full error message below)

Apparently, [networkx 2.8.4](https://pypi.org/project/networkx/2.8.4/) requires python >=3.8 which contradicts [longbow](https://pypi.org/project/maslongbow/)'s requirement using python <=3.7.9. Any idea, how I can properly resolve this?

Thanks in advance and have a nice day!
Philipp

```
pip3 install maslongbow
...
Collecting pomegranate (from maslongbow)
  Downloading https://files.pythonhosted.org/packages/e3/b2/77046c67df28005912ce0e1a2c005a42f560e1a81d888838adcf156cfefd/pomegranate-1.0.2-py3-none-any.whl (90kB)
...
Collecting networkx>=2.8.4 (from pomegranate->maslongbow)
  Could not find a version that satisfies the requirement networkx>=2.8.4 (from pomegranate->maslongbow) (from versions: 0.34, 0.35, 0.35.1, 0.36, 0.37, 0.99, 1.0rc1, 1.0, 1.0.1, 1.1, 1.2rc1, 1.2, 1.3rc1, 1.3, 1.4rc1, 1.4, 1.5rc1, 1.5, 1.6rc1, 1.6, 1.7rc1, 1.7, 1.8rc1, 1.8, 1.8.1, 1.9rc1, 1.9, 1.9.1, 1.10rc2, 1.10, 1.11rc1, 1.11rc2, 1.11, 2.0, 2.1, 2.2rc1, 2.2, 2.3rc3, 2.3rc4, 2.3, 2.4rc1, 2.4rc2, 2.4, 2.5rc1, 2.5, 2.5.1)
No matching distribution found for networkx>=2.8.4 (from pomegranate->maslongbow)
```

**Comment by jonn-smith** [comment]
Hi @phpeters.  I think the issue here is that the pip package isn't working properly.  I had to fork `pomegranate` to fix a seg fault in it and I don't think the pip packages were ever updated after this.

You're better off cloning this repo and installing from the local clone and / or just using the docker image.

**Comment by phpeters** [comment]
Hej @jonn-smith ,
Thanks for your message and the explanation! 
I ended up using the docker image and pulled it with singularity. Looks like it worked that way.
Thanks a lot!
Philipp
